### ISSUE TITLE
Upload file size limit

### ISSUE THREAD

**Issue by Soebb** [arandomliz/telegram-video-download-bot#4]
As you know, python-telegram-bot has a limit to upload the large files, although Pyrogram and Telethon haven't such limit.

**Comment by tyalie** [comment]
Which shouldn't pose a limit. There's a configurable maximum duration for downloading videos. The bot was designed with small things from TikTok, Instagram, Tumblr in mind. 

But you can adapt it if you want ^^

(Sorry for no readme yet)

**Comment by Soebb** [comment]
Aha thanks.

**Comment by tyalie** [comment]
I think the more feasible solution for your case would be to use a local telegram bot API server as described [in the telegram docs](https://core.telegram.org/bots/api#using-a-local-bot-api-server). There are also Docker container for that, but documentation is a bit sparse.

Using telegram API user clients is less stable (I talk from experience) needs a secondary account, ...
