### ISSUE TITLE
Throws error for pornhub.com

### ISSUE THREAD

**Issue by Soebb** [arandomliz/telegram-video-download-bot#5]
Nice work, i just report this to know.
[bot_logs.txt](https://github.com/arandomliz/telegram-video-download-bot/files/7999348/bot_logs.txt)

**Comment by tyalie** [comment]
Oh that's interesting. There's no total_bytes in the progress status 😳

Well. That's an easy fix thoo

**Comment by tyalie** [comment]
It should have been fixed now with https://github.com/arandomliz/telegram-video-download-bot/commit/1e8672067592da24c5e20fcc8aa23a401b1a792a
